### ISSUE TITLE
Neu Produkte Gruppe: Beauty

### ISSUE THREAD

**Issue by KolaSiro** [KolaSiro/Odnalaz#19]
Bitte neue Produktegruppe erfassen: Beauty

**Comment by KristijanDerGrosse** [comment]
@TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart @TiagosBart

**Comment by KolaSiro** [comment]
Integrated in master-branch.
